name = "sendpulse-proxy"
main = "functions/sendpulse-worker.js"
compatibility_date = "2024-12-13"
compatibility_flags = ["nodejs_compat"]

[vars]
SENDPULSE_USER_ID = "9524243"

[env.production]
vars = { ENVIRONMENT = "production", SENDPULSE_USER_ID = "9524243" }
